version: '3'
services:
  db:
    image: mysql:5.7.41
    hostname: ${dbdomain}.${host}
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${dbdomain}.${host}
    ports:
      - ${dbport}:${dbport}
    environment:
      MYSQL_ROOT_PASSWORD: ${dbpassword}
      MYSQL_USER: ${dbuser}
      MYSQL_PASSWORD: ${dbpassword}
      MYSQL_DATABASE: ${database}
    volumes: 
      - .init:/docker-entrypoint-initdb.d
    tty: true
  hivemq:
    image: hivemq/hivemq-ce
    ports:
      - ${hiveport}:${hiveport}
      - ${hiveportw}:${hiveportw}
    environment:
      - HIVEMQ_LOG_LEVEL=INFO
    hostname: ${hivedomain}.${host}
  fire-service:
    image: ${service}
    hostname: ${domain}.${host}
    container_name: ${domain}.${host}
    ports:
      - ${port}:${port}
    environment:
      - DATABASE=${database} 
      - HOST=${dbdomain}.${host} 
      - PORT=${dbport} 
      - USER=${dbuser}
      - PASSWORD=${dbpassword}
      - SERVICEHOST=${domain}.${host}
      - SERVICEPORT=${port}
      - HIVEMQ=${hivedomain}.${host}:${hiveport}
      - HUSERNAME=${husername}
      - HPASSWORD=${hpassword}
      - HCLIENT=${clientid}
      - HTOPIC=${htopic}
      - SECRETKEY=${secretkey}
    depends_on:
      - db
    tty: true
networks:
  backend:
    driver: bridge